@subcategory = Subcategory.create(:title=>"Bars", :category_id => 1)
@subcategory = Subcategory.create(:title=>"Cigar Clubs", :category_id => 1)
@subcategory = Subcategory.create(:title=>"Comedy Clubs", :category_id => 1)
@subcategory = Subcategory.create(:title=>"Dance Clubs", :category_id => 1)
@subcategory = Subcategory.create(:title=>"Other Bars", :category_id => 1)
@subcategory = Subcategory.create(:title=>"Sports Bars", :category_id => 1)
@subcategory = Subcategory.create(:title=>"Barbers", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Cosmetics & Beauty Supply", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Day Spas", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Eyelash Service", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Hair Removal", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Hair Salons", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Makeup Artists", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Massage", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Nail Salons", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Other Beauty", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Piercing", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Skin & Body Care", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Tanning", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Tattoo", :category_id => 2)
@subcategory = Subcategory.create(:title=>"Accountants", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Adult Education", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Advertising & Marketing", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Architects", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Banks & Credit Unions", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Career Counseling", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Couriers & Delivery Services", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Employment Agencies", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Entertainment", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Financial Advising", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Funeral Services & Cemeteries", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Graphic Design", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Insurance", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Interior Design", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Internet Service Providers", :category_id => 3)
@subcategory = Subcategory.create(:title=>"IT Services & Computer Repair", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Landscape Architects", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Lawyers", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Life Coach", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Notaries", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Other Services", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Payday Loans & Check Cashing", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Photographers", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Printing", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Private Investigation", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Public Relations", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Real Estate", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Recording & Rehearsal Studios", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Tutors, Teachers and Instructors", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Video/Film Production", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Web Design", :category_id => 3)
@subcategory = Subcategory.create(:title=>"Auto Detailing", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Auto Glass Services", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Auto Parts & Supplies", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Auto Repair", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Body Repair Shops", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Car Dealers", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Car Wash", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Gas & Service Stations", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Motorcycle Dealers", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Motorcycle Repair", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Oil Change Stations", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Other Car", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Parking", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Smog Check", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Stereo Installation", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Tires", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Towing", :category_id => 4)
@subcategory = Subcategory.create(:title=>"Appliance Repair", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Carpet Cleaning", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Ding Repair", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Dry Cleaners & Laundry", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Duct Cleaning", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Handyman", :category_id => 5)
@subcategory = Subcategory.create(:title=>"House Cleaning", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Maid Service", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Office Cleaning", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Other Cleaners & Fixers", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Pool Cleaners", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Sewing & Alterations", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Shoe Cobbler", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Tailors", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Vacuum Repair", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Watch Repair", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Window Washing", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Windshield Repair", :category_id => 5)
@subcategory = Subcategory.create(:title=>"Accessories", :category_id => 6)
@subcategory = Subcategory.create(:title=>"Big & Tall", :category_id => 6)
@subcategory = Subcategory.create(:title=>"Children", :category_id => 6)
@subcategory = Subcategory.create(:title=>"Costumes", :category_id => 6)
@subcategory = Subcategory.create(:title=>"Men & Women", :category_id => 6)
@subcategory = Subcategory.create(:title=>"Mens", :category_id => 6)
@subcategory = Subcategory.create(:title=>"Other Clothing", :category_id => 6)
@subcategory = Subcategory.create(:title=>"Shoes", :category_id => 6)
@subcategory = Subcategory.create(:title=>"Vintage", :category_id => 6)
@subcategory = Subcategory.create(:title=>"Women", :category_id => 6)
@subcategory = Subcategory.create(:title=>"Bagels & Donuts", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Bakeries", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Beer, Wine & Spirits", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Breweries", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Burgers", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Cafés", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Candy & Sweets", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Coffee & Tea", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Convenience Stores", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Delis", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Desserts", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Fast Food", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Food Delivery Services", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Food Trucks", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Grocery", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Ice Cream & Frozen Yogurt", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Internet Cafes", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Juice & Smoothies", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Other Food", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Pizza", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Sandwiches", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Tea", :category_id => 7)
@subcategory = Subcategory.create(:title=>"Acupuncture", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Chiropractors", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Counseling", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Dentists", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Doctors", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Family Medicine", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Home Health Care", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Hospitals", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Laser Eye Surgery", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Medical Spas", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Nutritionists", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Optometrists", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Other Health", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Personal Trainers", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Pharmacies", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Physical Therapy", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Physicians", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Psychiatrist", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Psychologist", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Speech Therapists", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Sports Medicine", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Therapists", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Weight Loss", :category_id => 8)
@subcategory = Subcategory.create(:title=>"Appliances", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Building Supplies", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Carpet & Flooring", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Child & Day Care", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Contractors", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Electricians", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Furniture Upholstery", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Garage Doors & Gates", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Gardeners", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Hardware Stores", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Heating & A/C", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Home Inspectors", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Junk Removal and Hauling", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Keys & Locksmiths", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Kitchen", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Landscaping", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Movers", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Nurseries", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Other Home & Office", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Painters", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Pest Control", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Plumbers", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Roofing", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Security Systems", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Shades & Blinds", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Shipping Centers", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Storage", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Tree Services", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Windows Installation", :category_id => 9)
@subcategory = Subcategory.create(:title=>"Bike Rentals", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Boat Charters", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Boating", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Car Racing", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Cards & Stationery", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Catering", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Climbing", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Diving", :category_id => 10)
@subcategory = Subcategory.create(:title=>"DJs", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Fishing", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Hiking", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Horse Riding", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Hotels", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Kayaking", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Mini Golf", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Other Fun Events", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Party & Event Planning Services", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Party Supplies", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Personal Chefs", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Skydiving", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Soccer", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Swimming", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Tennis", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Venues & Event Spaces", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Videographers", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Wedding Planning", :category_id => 10)
@subcategory = Subcategory.create(:title=>"Other Pets", :category_id => 11)
@subcategory = Subcategory.create(:title=>"Pet Food", :category_id => 11)
@subcategory = Subcategory.create(:title=>"Pet Services", :category_id => 11)
@subcategory = Subcategory.create(:title=>"Pet Stores", :category_id => 11)
@subcategory = Subcategory.create(:title=>"Veterinarians", :category_id => 11)
@subcategory = Subcategory.create(:title=>"Amusement Parks", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Aquariums", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Arcades", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Archery", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Botanical Gardens", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Bowling Alley", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Casinos", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Festivals", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Galleries", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Go Karting", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Golf & Tennis Clubs/Courses", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Gun Range", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Gym & Workouts", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Karaoke", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Movie Theatre", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Museums", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Music Venues", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Opera & Ballet", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Other Places to Go", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Performing Arts", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Pool Halls", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Psychics & Astrologers", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Skating Rinks", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Ski Resorts", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Sport & Recreation Camps", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Stadiums & Arenas", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Wineries", :category_id => 12)
@subcategory = Subcategory.create(:title=>"Zoos", :category_id => 12)
@subcategory = Subcategory.create(:title=>"African", :category_id => 13)
@subcategory = Subcategory.create(:title=>"American", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Argentine", :category_id => 13)
@subcategory = Subcategory.create(:title=>"BBQ", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Belgian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Brazilian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Breakfast", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Buffets", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Cajun", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Cambodian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Caribbean", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Chinese", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Creperies", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Cuban", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Diners", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Ethiopian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Filipino", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Fish & Chips", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Fondue", :category_id => 13)
@subcategory = Subcategory.create(:title=>"French", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Gastropubs", :category_id => 13)
@subcategory = Subcategory.create(:title=>"German", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Greek", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Hawaiian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Himalayan/Nepalese", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Hungarian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Indian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Indonesian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Italian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Japanese", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Korean", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Kosher", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Latin American", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Mediterranean", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Mexican", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Middle Eastern", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Mongolian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Moroccan", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Other Places to Eat", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Persian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Polish", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Portuguese", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Russian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Scandinavian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Seafood", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Soul Food", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Soup", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Southern", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Spanish", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Steakhouse", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Sushi Bars", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Taiwanese", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Tapas", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Tex Mex", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Thai", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Turkish", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Ukrainian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Vegan", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Vegetarian", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Vietnamese", :category_id => 13)
@subcategory = Subcategory.create(:title=>"Antiques", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Art Galleries", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Arts & Crafts", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Baby", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Books & Magazines", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Bridal", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Computers", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Department Stores", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Drugstores", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Electronics", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Eyewear & Opticians", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Fashion", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Flowers & Gifts", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Furniture", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Hobby Shops", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Home & Garden", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Jewelry & Watches", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Knitting Supplies", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Luggage", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Mobile Phones", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Musical Instruments", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Office Equipment", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Other Shopping", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Outlets", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Pawn Shops", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Personal Shopping", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Photography", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Sporting Goods", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Thrift Stores", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Tobacco", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Toy Stores", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Video", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Wholesale", :category_id => 14)
@subcategory = Subcategory.create(:title=>"Agents", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Airplanes", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Bed & Breakfast", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Campgrounds", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Car Rental", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Hostels", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Hotels & Motels", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Limos", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Other Travel", :category_id => 15)
@subcategory = Subcategory.create(:title=>"RV Rental", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Taxis", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Tours", :category_id => 15)
@subcategory = Subcategory.create(:title=>"Transportation", :category_id => 15)
@subcategory = Subcategory.create(:title =>"Travel Services", :category_id => 15)