# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

Subcategory.create(:title => "Auto Detailing", :category_id => 1)
Subcategory.create(:title => "Auto Glass Services", :category_id => 1)
Subcategory.create(:title => "Auto Parts and Supplies", :category_id => 1)
Subcategory.create(:title => "Auto Repair", :category_id => 1)
Subcategory.create(:title => "Body Shops", :category_id => 1)
Subcategory.create(:title => "Car Dealers", :category_id => 1)
Subcategory.create(:title => "Car Wash", :category_id => 1)
Subcategory.create(:title => "Gas and Service Stations", :category_id => 1)
Subcategory.create(:title => "Motorcycle Dealers", :category_id => 1)
Subcategory.create(:title => "Motorcycle Repair", :category_id => 1)
Subcategory.create(:title => "Oil Change Stations", :category_id => 1)
Subcategory.create(:title => "Parking", :category_id => 1)
Subcategory.create(:title => "Smog Check", :category_id => 1)
Subcategory.create(:title => "Stereo Installation", :category_id => 1)
Subcategory.create(:title => "Tires", :category_id => 1)
Subcategory.create(:title => "Towing", :category_id => 1)
Subcategory.create(:title => "Windshield Maintenance", :category_id => 1)

Subcategory.create(:title => "Barbers", :category_id => 2)
Subcategory.create(:title => "Cosmetics and Beauty Supply", :category_id => 2)
Subcategory.create(:title => "Day Spas", :category_id => 2)
Subcategory.create(:title => "Eyelash Service", :category_id => 2)
Subcategory.create(:title => "Hair Removal", :category_id => 2)
Subcategory.create(:title => "Hair Salons", :category_id => 2)
Subcategory.create(:title => "Makeup Artists", :category_id => 2)
Subcategory.create(:title => "Massage", :category_id => 2)
Subcategory.create(:title => "Medical Spas", :category_id => 2)
Subcategory.create(:title => "Nail Salons", :category_id => 2)
Subcategory.create(:title => "Piercing", :category_id => 2)
Subcategory.create(:title => "Skin Care", :category_id => 2)
Subcategory.create(:title => "Tanning", :category_id => 2)
Subcategory.create(:title => "Tattoo", :category_id => 2)

Subcategory.create(:title => "Arcades", :category_id => 3)
Subcategory.create(:title => "Galleries", :category_id => 3)
Subcategory.create(:title => "Casinos", :category_id => 3)
Subcategory.create(:title => "Cinema", :category_id => 3)
Subcategory.create(:title => "Festivals", :category_id => 3)
Subcategory.create(:title => "Museums", :category_id => 3)
Subcategory.create(:title => "Music Venues", :category_id => 3)
Subcategory.create(:title => "Opera and Ballet", :category_id => 3)
Subcategory.create(:title => "Performing Arts", :category_id => 3)
Subcategory.create(:title => "Psychics and Astrologers", :category_id => 3)
Subcategory.create(:title => "Stadiums and Arenas", :category_id => 3)
Subcategory.create(:title => "Wineries", :category_id => 3)

Subcategory.create(:title => "Child and Day Care", :category_id => 4)

Subcategory.create(:title => "Banks and Credit Unions", :category_id => 5)
Subcategory.create(:title => "Payday Loans and Check Cashing", :category_id => 5)
Subcategory.create(:title => "Financial Advising", :category_id => 5)
Subcategory.create(:title => "Insurance", :category_id => 5)
Subcategory.create(:title => "Investing", :category_id => 5)

Subcategory.create(:title => "Bagels", :category_id => 6)
Subcategory.create(:title => "Bakeries", :category_id => 6)
Subcategory.create(:title => "Beer, Wine and Spirits", :category_id => 6)
Subcategory.create(:title => "Breweries", :category_id => 6)
Subcategory.create(:title => "Coffee and Tea", :category_id => 6)
Subcategory.create(:title => "Convenience Stores", :category_id => 6)
Subcategory.create(:title => "Desserts", :category_id => 6)
Subcategory.create(:title => "Donuts", :category_id => 6)
Subcategory.create(:title => "Food Delivery Services", :category_id => 6)
Subcategory.create(:title => "Grocery", :category_id => 6)
Subcategory.create(:title => "Ice Cream and Frozen Yogurt", :category_id => 6)
Subcategory.create(:title => "Internet Cafes", :category_id => 6)
Subcategory.create(:title => "Juice and Smoothies", :category_id => 6)
Subcategory.create(:title => "Tea", :category_id => 6)
Subcategory.create(:title => "Wineries", :category_id => 6)

Subcategory.create(:title => "Acupuncture", :category_id => 7)
Subcategory.create(:title => "Chiropractors", :category_id => 7)
Subcategory.create(:title => "Counseling", :category_id => 7)
Subcategory.create(:title => "Dentists", :category_id => 7)
Subcategory.create(:title => "Doctors", :category_id => 7)
Subcategory.create(:title => "Home Health Care", :category_id => 7)
Subcategory.create(:title => "Hospitals", :category_id => 7)
Subcategory.create(:title => "Laser Eye Surgery", :category_id => 7)
Subcategory.create(:title => "Medical Spas", :category_id => 7)
Subcategory.create(:title => "Nutritionists", :category_id => 7)
Subcategory.create(:title => "Optometrists", :category_id => 7)
Subcategory.create(:title => "Physical Therapy", :category_id => 7)
Subcategory.create(:title => "Retirement Homes", :category_id => 7)
Subcategory.create(:title => "Speech Therapists", :category_id => 7)
Subcategory.create(:title => "Weight Loss", :category_id => 7)

Subcategory.create(:title => "Appliances and Repair", :category_id => 8)
Subcategory.create(:title => "Building Supplies", :category_id => 8)
Subcategory.create(:title => "Carpet Cleaning", :category_id => 8)
Subcategory.create(:title => "Carpet Installation", :category_id => 8)
Subcategory.create(:title => "Contractors", :category_id => 8)
Subcategory.create(:title => "Electricians", :category_id => 8)
Subcategory.create(:title => "Flooring", :category_id => 8)
Subcategory.create(:title => "Gardeners", :category_id => 8)
Subcategory.create(:title => "Handyman", :category_id => 8)
Subcategory.create(:title => "Heating and Air Conditioning/HVAC", :category_id => 8)
Subcategory.create(:title => "Home Cleaning", :category_id => 8)
Subcategory.create(:title => "Home Inspectors", :category_id => 8)
Subcategory.create(:title => "Home Theatre Installation", :category_id => 8)
Subcategory.create(:title => "Interior Design", :category_id => 8)
Subcategory.create(:title => "Internet Service Providers", :category_id => 8)
Subcategory.create(:title => "Keys and Locksmiths", :category_id => 8)
Subcategory.create(:title => "Landscape Architects", :category_id => 8)
Subcategory.create(:title => "Landscaping", :category_id => 8)
Subcategory.create(:title => "Lighting Fixtures and Equipment", :category_id => 8)
Subcategory.create(:title => "Movers", :category_id => 8)
Subcategory.create(:title => "Painters", :category_id => 8)
Subcategory.create(:title => "Plumbing", :category_id => 8)
Subcategory.create(:title => "Pool Cleaners", :category_id => 8)
Subcategory.create(:title => "Real Estate", :category_id => 8)
Subcategory.create(:title => "Roofing", :category_id => 8)
Subcategory.create(:title => "Security Systems", :category_id => 8)
Subcategory.create(:title => "Self Storage", :category_id => 8)
Subcategory.create(:title => "Shades and Blinds", :category_id => 8)
Subcategory.create(:title => "Solar Installation", :category_id => 8)
Subcategory.create(:title => "Television Service Providers", :category_id => 8)
Subcategory.create(:title => "Tree Services", :category_id => 8)
Subcategory.create(:title => "Window Washing", :category_id => 8)
Subcategory.create(:title => "Windows Installation", :category_id => 8)

Subcategory.create(:title => "Child Care and Day Care", :category_id => 9)
Subcategory.create(:title => "Community Service/Non-Profit", :category_id => 9)
Subcategory.create(:title => "Couriers and Delivery Services", :category_id => 9)
Subcategory.create(:title => "Dry Cleaning and Laundry", :category_id => 9)

Subcategory.create(:title => "Adult Entertainment", :category_id => 10)
Subcategory.create(:title => "Bars", :category_id => 10)
Subcategory.create(:title => "Comedy Clubs", :category_id => 10)
Subcategory.create(:title => "Dance Clubs", :category_id => 10)
Subcategory.create(:title => "Jazz and Blues", :category_id => 10)
Subcategory.create(:title => "Karaoke", :category_id => 10)
Subcategory.create(:title => "Music Venues", :category_id => 10)
Subcategory.create(:title => "Pool Halls", :category_id => 10)
Subcategory.create(:title => "Live Music", :category_id => 10)

Subcategory.create(:title => "Boat Charters", :category_id => 11)
Subcategory.create(:title => "Cards and Stationery", :category_id => 11)
Subcategory.create(:title => "Catering", :category_id => 11)
Subcategory.create(:title => "DJs", :category_id => 11)
Subcategory.create(:title => "Hotels", :category_id => 11)
Subcategory.create(:title => "Party and Event Planning Services", :category_id => 11)	
Subcategory.create(:title => "Party Supplies", :category_id => 11)
Subcategory.create(:title => "Personal Chefs", :category_id => 11)
Subcategory.create(:title => "Photographers", :category_id => 11)
Subcategory.create(:title => "Venues and Event Spaces", :category_id => 11)
Subcategory.create(:title => "Videographers", :category_id => 11)
Subcategory.create(:title => "Wedding Planning", :category_id => 11)

Subcategory.create(:title => "Pet Food", :category_id => 12)
Subcategory.create(:title => "Pet Services", :category_id => 12)
Subcategory.create(:title => "Pet Stores", :category_id => 12)
Subcategory.create(:title => "Veterinarians", :category_id => 12)

Subcategory.create(:title => "Accountants", :category_id => 13)
Subcategory.create(:title => "Advertising", :category_id => 13)
Subcategory.create(:title => "Architects", :category_id => 13)
Subcategory.create(:title => "Career Counseling", :category_id => 13)
Subcategory.create(:title => "Electronics Repair", :category_id => 13)
Subcategory.create(:title => "Employment Agencies", :category_id => 13)
Subcategory.create(:title => "Funeral Services and Cemeteries", :category_id => 13)
Subcategory.create(:title => "Furniture Upholstery", :category_id => 13)
Subcategory.create(:title => "Graphic Design", :category_id => 13)
Subcategory.create(:title => "Internet Service Providers", :category_id => 13)
Subcategory.create(:title => "IT Services and Computer Repair", :category_id => 13)
Subcategory.create(:title => "Junk Removal and Hauling", :category_id => 13)
Subcategory.create(:title => "Lawyers", :category_id => 13)
Subcategory.create(:title => "Life Coach", :category_id => 13)
Subcategory.create(:title => "Marketing", :category_id => 13)
Subcategory.create(:title => "Notaries", :category_id => 13)
Subcategory.create(:title => "Office Cleaning", :category_id => 13)
Subcategory.create(:title => "Pest Control", :category_id => 13)
Subcategory.create(:title => "Printing", :category_id => 13)
Subcategory.create(:title => "Private Investigation", :category_id => 13)
Subcategory.create(:title => "Public Relations", :category_id => 13)
Subcategory.create(:title => "Recording and Rehearsal Studios", :category_id => 13)
Subcategory.create(:title => "Sewing and Alterations", :category_id => 13)
Subcategory.create(:title => "Shipping Centers", :category_id => 13)
Subcategory.create(:title => "Shoe Repair", :category_id => 13)
Subcategory.create(:title => "Video/Film Production", :category_id => 13)
Subcategory.create(:title => "Watch Repair", :category_id => 13)
Subcategory.create(:title => "Web Design", :category_id => 13)

Subcategory.create(:title => "African", :category_id => 14)
Subcategory.create(:title => "American", :category_id => 14)
Subcategory.create(:title => "Argentine", :category_id => 14)
Subcategory.create(:title => "BBQ", :category_id => 14)
Subcategory.create(:title => "Belgian", :category_id => 14)
Subcategory.create(:title => "Brazilian", :category_id => 14)
Subcategory.create(:title => "Breakfast", :category_id => 14)
Subcategory.create(:title => "Buffets", :category_id => 14)
Subcategory.create(:title => "Burgers", :category_id => 14)
Subcategory.create(:title => "Cajun", :category_id => 14)
Subcategory.create(:title => "Cambodian", :category_id => 14)
Subcategory.create(:title => "Caribbean", :category_id => 14)
Subcategory.create(:title => "Chinese", :category_id => 14)
Subcategory.create(:title => "Creperies", :category_id => 14)
Subcategory.create(:title => "Cuban", :category_id => 14)
Subcategory.create(:title => "Delis", :category_id => 14)
Subcategory.create(:title => "Diners", :category_id => 14)
Subcategory.create(:title => "Ethiopian", :category_id => 14)
Subcategory.create(:title => "Fast Food", :category_id => 14)
Subcategory.create(:title => "Filipino", :category_id => 14)
Subcategory.create(:title => "Fish and Chips", :category_id => 14)
Subcategory.create(:title => "Fondue", :category_id => 14)
Subcategory.create(:title => "Food Truck", :category_id => 14)
Subcategory.create(:title => "French", :category_id => 14)
Subcategory.create(:title => "Gastropubs", :category_id => 14)
Subcategory.create(:title => "German", :category_id => 14)
Subcategory.create(:title => "Greek", :category_id => 14)
Subcategory.create(:title => "Hawaiian", :category_id => 14)
Subcategory.create(:title => "Himalayan/Nepalese", :category_id => 14)
Subcategory.create(:title => "Hungarian", :category_id => 14)
Subcategory.create(:title => "Indian", :category_id => 14)
Subcategory.create(:title => "Indonesian", :category_id => 14)
Subcategory.create(:title => "Italian", :category_id => 14)
Subcategory.create(:title => "Japanese", :category_id => 14)
Subcategory.create(:title => "Korean", :category_id => 14)
Subcategory.create(:title => "Kosher", :category_id => 14)
Subcategory.create(:title => "Latin American", :category_id => 14)
Subcategory.create(:title => "Mediterranean", :category_id => 14)
Subcategory.create(:title => "Mexican", :category_id => 14)
Subcategory.create(:title => "Middle Eastern", :category_id => 14)
Subcategory.create(:title => "Mongolian", :category_id => 14)
Subcategory.create(:title => "Moroccan", :category_id => 14)
Subcategory.create(:title => "Persian", :category_id => 14)
Subcategory.create(:title => "Pizza", :category_id => 14)
Subcategory.create(:title => "Polish", :category_id => 14)
Subcategory.create(:title => "Portuguese", :category_id => 14)
Subcategory.create(:title => "Russian", :category_id => 14)
Subcategory.create(:title => "Sandwiches", :category_id => 14)
Subcategory.create(:title => "Scandinavian", :category_id => 14)
Subcategory.create(:title => "Seafood", :category_id => 14)
Subcategory.create(:title => "Soul Food", :category_id => 14)
Subcategory.create(:title => "Soup", :category_id => 14)
Subcategory.create(:title => "Southern", :category_id => 14)
Subcategory.create(:title => "Spanish", :category_id => 14)
Subcategory.create(:title => "Steakhouse", :category_id => 14)
Subcategory.create(:title => "Sushi Bars", :category_id => 14)
Subcategory.create(:title => "Taiwanese", :category_id => 14)
Subcategory.create(:title => "Tapas", :category_id => 14)
Subcategory.create(:title => "Tex Mex", :category_id => 14)
Subcategory.create(:title => "Thai", :category_id => 14)
Subcategory.create(:title => "Turkish", :category_id => 14)
Subcategory.create(:title => "Ukrainian", :category_id => 14)
Subcategory.create(:title => "Vegan", :category_id => 14)
Subcategory.create(:title => "Vegetarian", :category_id => 14)
Subcategory.create(:title => "Vietnamese", :category_id => 14)

Subcategory.create(:title => "Adult Education", :category_id => 15)
Subcategory.create(:title => "Colleges and Universities", :category_id => 15)
Subcategory.create(:title => "Educational Services", :category_id => 15)
Subcategory.create(:title => "Elementary Schools", :category_id => 15)
Subcategory.create(:title => "Middle Schools and High Schools", :category_id => 15)
Subcategory.create(:title => "Preschools", :category_id => 15)
Subcategory.create(:title => "Private Tutors", :category_id => 15)
Subcategory.create(:title => "Specialty Schools", :category_id => 15)
Subcategory.create(:title => "Tutoring Centers", :category_id => 15)

Subcategory.create(:title => "Adult", :category_id => 16)
Subcategory.create(:title => "Antiques", :category_id => 16)
Subcategory.create(:title => "Art Galleries", :category_id => 16)
Subcategory.create(:title => "Arts and Crafts", :category_id => 16)	
Subcategory.create(:title => "Baby", :category_id => 16)
Subcategory.create(:title => "Beauty Supplies", :category_id => 16)
Subcategory.create(:title => "Books and Magazines", :category_id => 16)
Subcategory.create(:title => "Bridal", :category_id => 16)
Subcategory.create(:title => "Computers", :category_id => 16)
Subcategory.create(:title => "Cosmetics", :category_id => 16)
Subcategory.create(:title => "Department Stores", :category_id => 16)
Subcategory.create(:title => "Drugstores", :category_id => 16)
Subcategory.create(:title => "Electronics", :category_id => 16)
Subcategory.create(:title => "Eyewear and Opticians", :category_id => 16)
Subcategory.create(:title => "Fashion", :category_id => 16)
Subcategory.create(:title => "Flowers and Gifts", :category_id => 16)
Subcategory.create(:title => "Furniture", :category_id => 16)
Subcategory.create(:title => "Hobby Shops", :category_id => 16)
Subcategory.create(:title => "Home and Garden", :category_id => 16)
Subcategory.create(:title => "Jewelry", :category_id => 16)
Subcategory.create(:title => "Knitting Supplies", :category_id => 16)
Subcategory.create(:title => "Luggage", :category_id => 16)
Subcategory.create(:title => "Mobile Phones", :category_id => 16)
Subcategory.create(:title => "Musical Instruments", :category_id => 16)
Subcategory.create(:title => "Office Equipment", :category_id => 16)
Subcategory.create(:title => "Outlets", :category_id => 16)
Subcategory.create(:title => "Pawn Shops", :category_id => 16)
Subcategory.create(:title => "Personal Shopping", :category_id => 16)
Subcategory.create(:title => "Photography", :category_id => 16)
Subcategory.create(:title => "Sporting Goods", :category_id => 16)
Subcategory.create(:title => "Thrift Stores", :category_id => 16)
Subcategory.create(:title => "Tobacco", :category_id => 16)
Subcategory.create(:title => "Toy Stores", :category_id => 16)
Subcategory.create(:title => "Video", :category_id => 16)
Subcategory.create(:title => "Watches", :category_id => 16)
Subcategory.create(:title => "Wholesale", :category_id => 16)

Subcategory.create(:title => "Amusement Parks", :category_id => 17)
Subcategory.create(:title => "Aquariums", :category_id => 17)
Subcategory.create(:title => "Archery", :category_id => 17)
Subcategory.create(:title => "Bike Rentals", :category_id => 17)
Subcategory.create(:title => "Boating", :category_id => 17)
Subcategory.create(:title => "Bowling", :category_id => 17)
Subcategory.create(:title => "Climbing", :category_id => 17)
Subcategory.create(:title => "Diving", :category_id => 17)
Subcategory.create(:title => "Fishing", :category_id => 17)
Subcategory.create(:title => "Go Karting", :category_id => 17)
Subcategory.create(:title => "Golf", :category_id => 17)
Subcategory.create(:title => "Gun Range", :category_id => 17)
Subcategory.create(:title => "Hiking", :category_id => 17)
Subcategory.create(:title => "Horse Riding", :category_id => 17)
Subcategory.create(:title => "Kayaking", :category_id => 17)
Subcategory.create(:title => "Mini Golf", :category_id => 17)
Subcategory.create(:title => "Personal Trainers", :category_id => 17)
Subcategory.create(:title => "Skating Rinks", :category_id => 17)
Subcategory.create(:title => "Skydiving", :category_id => 17)
Subcategory.create(:title => "Soccer", :category_id => 17)
Subcategory.create(:title => "Sport Camps", :category_id => 17)
Subcategory.create(:title => "Swimming", :category_id => 17)
Subcategory.create(:title => "Tennis", :category_id => 17)
Subcategory.create(:title => "Zoos", :category_id => 17)

Subcategory.create(:title => "Airports", :category_id => 18)
Subcategory.create(:title => "Bed and Breakfast", :category_id => 18)
Subcategory.create(:title => "Campgrounds", :category_id => 18)
Subcategory.create(:title => "Car Rental", :category_id => 18)
Subcategory.create(:title => "Hostels", :category_id => 18)
Subcategory.create(:title => "Hotels", :category_id => 18)
Subcategory.create(:title => "RV Rental", :category_id => 18)
Subcategory.create(:title => "Ski Resorts", :category_id => 18)
Subcategory.create(:title => "Tours", :category_id => 18)
Subcategory.create(:title => "Transportation", :category_id => 18)
Subcategory.create(:title => "Travel Services", :category_id => 18)
Subcategory.create(:title => "Vacation Rental Agents", :category_id => 18)